### ISSUE TITLE
Uploading a new rockspec file still picks the old one

### ISSUE THREAD

**Issue by thefosk** [leafo/moonrocks-site#36]
I am experiencing the following weird issue when using Chrome:

* I upload a `rockspec` for the first time, everything works great.
* I discover a typo in my `rockspec` file, so I delete the project and re-upload the new updated `rockspec` file (with the same filename) under the same project name
* The moonrocks site doesn't detect the new changes of the newly uploaded file and still show the old `rockspec` file despite having uploaded a new one

I don't know what it's going on, maybe the old `rockspec` file is being cached the first time and uploading it again with a different content doesn't actually override the cache and still picks the old content?

**Comment by moteus** [comment]
I just faced with same issues.
I try web interface and luarocks upload command.

**Comment by moteus** [comment]
Even after I delete specific verision (scm-0) of my module (via Web) and upload it again with new rockspec I still get old one

**Comment by thefosk** [comment]
@leafo pinging you on this since it is a critical issue, it prevents updating a `rockspec`.

**Comment by leafo** [comment]
I don't think you should be changing the contents of a rockspec after you deploy it. Imagine it gets uploaded and cached across all of our mirrors in the time between you discovering a typo. The luarocks protocol has no information about dates on rockspecs so you're pretty much screwed. I can fix it in this case but I don't recommend doing it, increment the number at the end of the file.

**Comment by moteus** [comment]
I talk about scm rockspecs. This rockspecs should build current master of module. So when I change module (e.g. add new file/rename existing one) I have to update scm rockspec too. Also old rockspec did not work any more and become useless and there not reason to keep it. So replce this rockspec is best way.

PS. new rockspec start beeng avaliable after ~30 minutes after uploading.

**Comment by leafo** [comment]
The same problem exists for SCM rockspecs. I've deployed code that keeps track of the upload revision and busts the cache on moonrocks, but it will not affect any cached copies of the rockspecs/modules.

**Comment by thefosk** [comment]
The same issue is still happening. How to replicate:

* Create a brand-new module, upload the `rockspec` file.
* Delete the module
* Upload a new `rockspec` with, for example, a different description. This effectively re-creates the module on the site.
* Inspecting the `rockspec` file on Moonrocks still shows the old one.

**Comment by adityaramesh** [comment]
I'm also experiencing this problem. If I make a chance to a rockspecs file on a Github repository, it takes Luarocks some time in order to download the new file rather than continue using the cached version. This makes debugging rockspecs files rather irritating.
